# Require the AWS provider plugin
require 'vagrant-aws'

# Create and configure the AWS instance(s)
Vagrant.configure('2') do |config|
  # Use dummy AWS box
  config.vm.box = 'aws-dummy'
  config.aws_credentials.profile = "default"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Specify AWS provider configuration
  config.vm.provider 'aws' do |aws, override|
    aws.region = 'us-east-2'
    aws.instance_type = 't2.micro'
    aws.keypair_name = 'id_rsa'
    aws.security_groups = ['default']
    aws.terminate_on_shutdown = true
    aws.ami = `cat ../dev/ami.txt`
    aws.user_data = `cat test.py`
    aws.iam_instance_profile_name = 'ol-test-vm'

    override.ssh.username = 'ubuntu'
    override.ssh.private_key_path = '~/.ssh/id_rsa'
    override.nfs.functional = false
  end
end
